# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_card.ipynb 2
from nbdev.showdoc import *
from fastcore.test import *
from fastcore.utils import *

# %% ../nbs/00_card.ipynb 3
suits = 'spade, clover, diamond, heart'.split(',')
ranks = [None, 'A'] + [str(x) for x in range(2, 11)] + ['J', 'Q', 'K']

# %% ../nbs/00_card.ipynb 12
class Card:
    '''
    bla bla 
    '''

    def __init__(self, 
                 suit: int, # index into `suits`
                 rank: int  # index into `ranks`
                 ) -> None:
        self.suit = suit
        self.rank = rank
    
    def __str__(self) -> str:
        return f'{ranks[self.rank]}{suits[self.suit]}'

    def __repr__(self) -> str:
        return f'{ranks[self.rank]}{suits[self.suit]}'
    
    def __eq__(self, a) -> bool:
        return (self.suit, self.rank) == (a.suit, a.rank)

# %% ../nbs/00_card.ipynb 18
@patch
def __eq__(self:Card, a: Card) -> bool:
    return (self.suit, self.rank) == (a.suit, a.rank)

@patch
def __lt__(self:Card, a: object) -> bool:
    return (self.rank, self.suit) < (a.suit, a.rank)
